// api/dashboard.js - Sizemill admin dashboard (v1.0)
// Served at /admin (vercel.json rewrite). Holds no secrets: the page asks for the
// admin secret, keeps it in sessionStorage, and sends it to /api/admin on every call.
// Sections: members and health, platform book, insights, activity, snapshots,
// infrastructure (Supabase, edge functions, deployment), audit log, invite.

export default function handler(req, res) {
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store');
  res.setHeader('X-Frame-Options', 'DENY');
  res.setHeader('Referrer-Policy', 'no-referrer');
  res.status(200).send(html);
}

const html = '<!DOCTYPE html>\n<html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Sizemill \u2014 Admin</title>' +
'<link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">' +
'<style>' +
':root{--paper:#F5F7FA;--surface:#FFFFFF;--ink:#10233F;--ink-2:#4A5A72;--ink-3:#8A97AB;--line:#E4E9F0;--line-2:#D3DBE6;--signal:#2E5BFF;--signal-tint:#EDF1FF;--gain:#0FA37F;--gain-tint:#E6F6F0;--loss:#E24B4B;--loss-tint:#FCEBEB;--warn:#C98A00;--warn-tint:#FFF5DE;--r:10px;--rc:5px;--sans:"IBM Plex Sans",-apple-system,"Segoe UI",Helvetica,Arial,sans-serif;--mono:"IBM Plex Mono",ui-monospace,SFMono-Regular,Menlo,monospace}' +
'*{box-sizing:border-box;margin:0;padding:0}html,body{height:100%}body{font-family:var(--sans);font-size:14px;line-height:1.45;color:var(--ink);background:var(--paper);font-variant-numeric:tabular-nums;-webkit-font-smoothing:antialiased}' +
'button{font:inherit;color:inherit;background:none;border:0;cursor:pointer}input,select{font:inherit;color:inherit}a{color:var(--signal);text-decoration:none}' +
'.gate{position:fixed;inset:0;background:#fff;display:flex;align-items:center;justify-content:center;z-index:50}.gate.hidden{display:none}.gatebox{width:320px;text-align:center}.mark{width:34px;height:34px;border-radius:9px;background:var(--ink);position:relative;margin:0 auto 14px}.mark::after{content:"";position:absolute;inset:9px;border-radius:50%;background:#fff}.gatebox h1{font-size:24px;font-weight:600;letter-spacing:-.02em;margin-bottom:4px}.gatebox p{color:var(--ink-3);font-size:13px;margin-bottom:30px}.gatebox input{width:100%;border:1px solid var(--line-2);border-radius:var(--rc);padding:10px 12px;font-size:14px;text-align:center;margin-bottom:10px}.gatebox .btn{width:100%;justify-content:center;padding:10px 12px;font-size:14px}.gatebox .msg{margin-top:14px;font-size:12.5px;color:var(--loss);min-height:18px}' +
'.btn{border:1px solid var(--ink);background:var(--ink);color:#fff;border-radius:var(--rc);padding:7px 12px;font-size:13px;display:inline-flex;align-items:center;gap:7px}.btn.secondary{background:var(--surface);color:var(--ink);border-color:var(--line-2)}.btn.secondary:hover{border-color:var(--ink-3)}.btn.danger{background:var(--loss);border-color:var(--loss)}.btn.sm{padding:4px 9px;font-size:12px}.btn:disabled{opacity:.5;cursor:default}.link{color:var(--signal);font-size:13px}.link.mute{color:var(--ink-3)}' +
'.top{position:sticky;top:0;z-index:10;background:var(--surface);border-bottom:1px solid var(--line);height:52px;display:flex;align-items:center;gap:18px;padding:0 22px}.top .brand{display:flex;align-items:center;gap:10px;font-weight:600}.top .brand .mark{width:22px;height:22px;border-radius:6px;margin:0}.top .brand .mark::after{inset:6px}.top .brand small{font-weight:400;color:var(--ink-3);margin-left:6px}.top nav{display:flex;gap:4px;margin-left:8px;overflow:auto}.top nav a{color:var(--ink-2);padding:6px 10px;border-radius:var(--rc);font-size:13px;white-space:nowrap}.top nav a:hover{background:var(--paper);color:var(--ink)}.top .sp{flex:1}.top .meta{font-size:12px;color:var(--ink-3);white-space:nowrap}.top .meta b{color:var(--ink-2);font-weight:500}' +
'.main{max-width:1440px;margin:0 auto;padding:22px}h2.sec{font-size:13px;font-weight:500;color:var(--ink-3);text-transform:none;margin:26px 0 10px;letter-spacing:.01em}h2.sec:first-child{margin-top:0}' +
'.kpis{display:grid;grid-template-columns:repeat(8,1fr);background:var(--surface);border:1px solid var(--line);border-radius:var(--r);overflow:hidden}.kpi{padding:14px 16px;border-right:1px solid var(--line)}.kpi:last-child{border-right:0}.kpi .l{font-size:12px;color:var(--ink-3);margin-bottom:6px}.kpi .v{font-size:22px;font-weight:500;letter-spacing:-.01em;line-height:1.1}.kpi .v.up{color:var(--gain)}.kpi .v.dn{color:var(--loss)}.kpi .s{font-size:12px;color:var(--ink-2);margin-top:6px}' +
'.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}.c12{grid-column:span 12}.c8{grid-column:span 8}.c6{grid-column:span 6}.c4{grid-column:span 4}.panel{background:var(--surface);border:1px solid var(--line);border-radius:var(--r);padding:16px 18px;min-width:0}.panel.tight{padding:0}.panel.tight .ph{padding:14px 18px 10px}.ph{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin-bottom:10px}.ph h3{font-size:14.5px;font-weight:600}.ph .sub{font-size:12px;color:var(--ink-3);text-align:right}' +
'table{width:100%;border-collapse:collapse;font-size:13px}th{font-weight:500;color:var(--ink-3);text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);white-space:nowrap;font-size:12px}td{padding:9px 10px;border-bottom:1px solid var(--line);vertical-align:middle;white-space:nowrap}tr:last-child td{border-bottom:0}.r{text-align:right}tr.row{cursor:pointer}tr.row:hover td{background:var(--paper)}.tick{font-family:var(--mono);font-size:12px}.small{font-size:12px;color:var(--ink-3)}.up{color:var(--gain)}.dn{color:var(--loss)}.mute{color:var(--ink-3)}.pill{display:inline-block;font-size:11.5px;padding:2px 8px;border-radius:10px;background:var(--paper);color:var(--ink-2);border:1px solid var(--line)}.pill.green{background:var(--gain-tint);color:var(--gain);border-color:transparent}.pill.amber{background:var(--warn-tint);color:var(--warn);border-color:transparent}.pill.red{background:var(--loss-tint);color:var(--loss);border-color:transparent}.pill.blue{background:var(--signal-tint);color:var(--signal);border-color:transparent}' +
'.dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:8px;vertical-align:middle}.dot.green{background:var(--gain)}.dot.amber{background:var(--warn)}.dot.red{background:var(--loss)}.dot.grey{background:var(--ink-3)}' +
'.alist{display:flex;flex-direction:column}.al{display:flex;gap:12px;padding:10px 0;border-bottom:1px solid var(--line);align-items:flex-start}.al:last-child{border-bottom:0}.al .sig{width:8px;height:8px;border-radius:50%;margin-top:6px;flex:none;background:var(--ink-3)}.al .sig.gain{background:var(--gain)}.al .sig.warn{background:var(--warn)}.al .sig.loss{background:var(--loss)}.al .sig.info{background:var(--signal)}.al .t{font-weight:500}.al .d{font-size:12.5px;color:var(--ink-2);margin-top:2px}' +
'.toolbar{display:flex;gap:10px;align-items:center;padding:10px 18px;border-bottom:1px solid var(--line);flex-wrap:wrap}.search{border:1px solid var(--line-2);border-radius:var(--rc);padding:5px 10px;font-size:13px;min-width:220px;background:var(--surface)}.chips{display:flex;gap:4px}.chips button{border:1px solid var(--line-2);border-radius:20px;padding:3px 10px;font-size:12px;color:var(--ink-2);background:var(--surface)}.chips button.on{background:var(--ink);color:#fff;border-color:var(--ink)}.toolbar .sp{flex:1}' +
'.bars{display:flex;align-items:flex-end;gap:2px;height:72px}.bars i{flex:1;background:var(--signal);opacity:.85;border-radius:2px 2px 0 0;min-height:1px}.bars i.zero{background:var(--line)}.stat-row{display:flex;gap:22px;flex-wrap:wrap}.stat .l{font-size:12px;color:var(--ink-3)}.stat .v{font-size:18px;font-weight:500}.stat .v small{font-size:11px;color:var(--ink-3);margin-left:4px;font-weight:400}' +
'.form{display:grid;grid-template-columns:repeat(12,1fr);gap:10px}.f{display:flex;flex-direction:column;gap:4px}.f label{font-size:12px;color:var(--ink-2)}.f input{border:1px solid var(--line-2);border-radius:var(--rc);padding:7px 9px;font-size:13px;background:var(--surface)}' +
'.drawer{position:fixed;top:0;right:0;bottom:0;width:560px;max-width:100%;background:var(--surface);border-left:1px solid var(--line);transform:translateX(100%);transition:transform .18s ease;z-index:40;display:flex;flex-direction:column}.drawer.open{transform:none}.dh{display:flex;align-items:center;justify-content:space-between;padding:14px 18px;border-bottom:1px solid var(--line)}.dh h3{font-size:15px;font-weight:600}.db{flex:1;overflow:auto;padding:16px 18px}.dsec{margin-bottom:22px}.dsec h4{font-size:12px;color:var(--ink-3);font-weight:500;margin-bottom:8px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.metric{background:var(--paper);border-radius:8px;padding:10px 12px}.metric .l{font-size:11.5px;color:var(--ink-3)}.metric .v{font-size:16px;font-weight:500;margin-top:2px}.btnrow{display:flex;gap:8px;flex-wrap:wrap}.overlay{position:fixed;inset:0;background:rgba(16,35,63,.25);z-index:30;display:none}.overlay.open{display:block}' +
'.modal{position:fixed;inset:0;display:none;align-items:center;justify-content:center;z-index:60}.modal.open{display:flex}.mbox{background:var(--surface);border-radius:12px;padding:22px;width:460px;max-width:92vw;box-shadow:0 20px 60px rgba(16,35,63,.25)}.mbox h3{font-size:16px;margin-bottom:8px}.mbox p{font-size:13px;color:var(--ink-2);margin-bottom:12px}.acts{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%);background:var(--ink);color:#fff;padding:10px 16px;border-radius:8px;font-size:13px;opacity:0;transition:opacity .2s;z-index:70;pointer-events:none}.toast.show{opacity:1}.note{background:var(--paper);border-radius:8px;padding:10px 12px;font-size:12.5px;color:var(--ink-2)}.empty{padding:22px;text-align:center;color:var(--ink-3);font-size:13px}.code{font-family:var(--mono);font-size:12px;background:var(--paper);padding:2px 6px;border-radius:4px;word-break:break-all}' +
'@media(max-width:1100px){.kpis{grid-template-columns:repeat(4,1fr)}.kpi:nth-child(4n){border-right:0}.c8,.c6,.c4{grid-column:span 12}.top nav{display:none}}' +
'</style></head><body>' +
'<div class="gate" id="gate"><div class="gatebox"><div class="mark"></div><h1>Sizemill</h1><p>Admin</p><input id="g_secret" type="password" placeholder="Admin secret" autocomplete="current-password"><button class="btn" id="g_go">Open</button><div class="msg" id="g_msg"></div></div></div>' +
'<div class="top"><div class="brand"><div class="mark"></div>Sizemill<small>Admin</small></div><nav><a href="#members">Members</a><a href="#book">Platform book</a><a href="#activity">Activity</a><a href="#snapshots">Snapshots</a><a href="#infra">Infrastructure</a><a href="#audit">Audit</a></nav><div class="sp"></div><div class="meta" id="topMeta"></div><button class="btn secondary sm" id="refresh">Refresh</button><button class="btn secondary sm" id="csv">Export CSV</button><button class="link mute" id="lock" style="font-size:12px">Lock</button></div>' +
'<div class="main" id="main">' +
'<div class="kpis" id="kpis"></div>' +
'<div class="grid" style="margin-top:14px"><div class="panel c8"><div class="ph"><h3>Needs you</h3><span class="sub" id="insSub"></span></div><div class="alist" id="insights"></div></div><div class="panel c4"><div class="ph"><h3>This deployment</h3><span class="sub">Straight from Vercel</span></div><div id="deploy"></div></div></div>' +
'<h2 class="sec" id="members">Members</h2><div class="panel tight"><div class="toolbar"><input class="search" id="q" placeholder="Email, workspace"><div class="chips" id="chips"><button data-c="all" class="on">All</button><button data-c="live">Live</button><button data-c="demo">Demo</button><button data-c="red">Needs attention</button><button data-c="nobook">No book</button></div><div class="sp"></div><span class="small" id="mcount"></span></div><div style="overflow:auto"><table id="mtable"></table></div></div>' +
'<h2 class="sec" id="book">Platform book</h2><div class="grid"><div class="panel c12"><div class="ph"><h3>Every member\u2019s book, added up</h3><span class="sub">Gross figures from saved state; before fees and tax</span></div><div class="stat-row" id="platform"></div></div></div>' +
'<h2 class="sec" id="activity">Activity</h2><div class="grid"><div class="panel c6"><div class="ph"><h3>Saves, last 30 days</h3><span class="sub">Snapshots taken by the database, a floor on real activity</span></div><div class="bars" id="savesBars"></div><div class="small" id="savesSub" style="margin-top:6px"></div></div><div class="panel c6"><div class="ph"><h3>Sign-ups, last 30 days</h3><span class="sub" id="signupSub"></span></div><div class="bars" id="signupBars"></div><div class="small" id="actSub" style="margin-top:6px"></div></div></div>' +
'<h2 class="sec" id="snapshots">Snapshots</h2><div class="panel tight"><div class="ph"><h3>Latest versions the database is holding</h3><span class="sub">One every four hours while a member works, plus before fresh starts, restores and large deletions</span></div><div style="overflow:auto"><table id="htable"></table></div></div>' +
'<h2 class="sec" id="infra">Infrastructure</h2><div class="grid"><div class="panel c4"><div class="ph"><h3>Supabase</h3><span class="sub">London, eu-west-2</span></div><div id="sbBox"></div></div><div class="panel c4 tight"><div class="ph"><h3>Tables</h3><span class="sub">Rows and size on disk</span></div><table id="ttable"></table></div><div class="panel c4"><div class="ph"><h3>Edge functions</h3><span class="sub">Probed from this request</span></div><div id="fnBox"></div></div></div>' +
'<h2 class="sec" id="audit">Audit log</h2><div class="grid"><div class="panel c8 tight"><div class="ph"><h3>Admin actions</h3><span class="sub">Everything done from this page, with the IP it came from</span></div><div style="overflow:auto"><table id="atable"></table></div></div><div class="panel c4"><div class="ph"><h3>Invite a member</h3><span class="sub">Supabase sends the email</span></div><div class="form"><div class="f" style="grid-column:span 12"><label>Email</label><input id="inv_email" type="email" placeholder="name@club.co.uk"></div></div><div class="acts" style="justify-content:flex-start"><button class="btn" id="inv_go">Send invite</button></div><p class="small" style="margin-top:10px">They land on the sign-in page with their account already created; the first save writes their book.</p></div></div>' +
'</div>' +
'<div class="overlay" id="overlay"></div><div class="drawer" id="drawer"><div class="dh"><h3 id="dTitle"></h3><button class="btn secondary sm" id="dClose">Close</button></div><div class="db" id="dBody"></div></div>' +
'<div class="modal" id="modal"><div class="mbox" id="mbox"></div></div><div class="toast" id="toast"></div>' +
'<script>' +
'var DATA=null,SECRET=sessionStorage.getItem("sizemill_admin_secret")||"",Q="",CHIP="all";' +
'function $(s){return document.querySelector(s)}function $$(s){return Array.prototype.slice.call(document.querySelectorAll(s))}' +
'function esc(s){return String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}' +
'function gbp(n){n=Number(n)||0;return (n<0?"-":"")+"\\u00a3"+Math.round(Math.abs(n)).toLocaleString("en-GB")}' +
'function kb(b){b=Number(b)||0;return b>1e6?(b/1e6).toFixed(1)+" MB":Math.round(b/1024)+" KB"}' +
'function when(iso){if(!iso)return "\\u2014";var d=new Date(iso);return d.toLocaleDateString("en-GB",{day:"numeric",month:"short"})+" "+d.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}' +
'function ago(iso){if(!iso)return "never";var d=(Date.now()-new Date(iso).getTime())/864e5;if(d<1/24)return "just now";if(d<1)return Math.round(d*24)+"h ago";return Math.round(d)+"d ago"}' +
'function toast(t){var e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast._t);toast._t=setTimeout(function(){e.classList.remove("show")},2600)}' +
'function modal(h){$("#mbox").innerHTML=h;$("#modal").classList.add("open");$$("#mbox [data-close]").forEach(function(b){b.addEventListener("click",closeModal)})}function closeModal(){$("#modal").classList.remove("open")}' +
'function openDrawer(t,h){$("#dTitle").textContent=t;$("#dBody").innerHTML=h;$("#drawer").classList.add("open");$("#overlay").classList.add("open")}function closeDrawer(){$("#drawer").classList.remove("open");$("#overlay").classList.remove("open")}' +
'$("#dClose").addEventListener("click",closeDrawer);$("#overlay").addEventListener("click",closeDrawer);$("#modal").addEventListener("click",function(e){if(e.target.id==="modal")closeModal()});document.addEventListener("keydown",function(e){if(e.key==="Escape"){closeModal();closeDrawer()}});' +
'async function api(body){var r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json","x-admin-secret":SECRET},body:JSON.stringify(body||{})});var j=null;try{j=await r.json()}catch(e){}if(r.status===401){lock();throw new Error("Admin secret rejected")}if(!r.ok||!j||j.error)throw new Error((j&&j.error)||("HTTP "+r.status));return j}' +
'function lock(){SECRET="";sessionStorage.removeItem("sizemill_admin_secret");$("#gate").classList.remove("hidden");$("#g_secret").value="";$("#g_msg").textContent=""}' +
'$("#lock").addEventListener("click",lock);' +
'async function unlock(){var s=$("#g_secret").value;if(!s){$("#g_msg").textContent="Secret, please.";return}$("#g_go").disabled=true;$("#g_msg").textContent="";try{var r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json","x-admin-secret":s},body:JSON.stringify({action:"check"})});var j=null;try{j=await r.json()}catch(e){}if(!r.ok){$("#g_msg").textContent=(j&&j.error)||("HTTP "+r.status);return}SECRET=s;sessionStorage.setItem("sizemill_admin_secret",s);$("#gate").classList.add("hidden");load()}finally{$("#g_go").disabled=false}}' +
'$("#g_go").addEventListener("click",unlock);$("#g_secret").addEventListener("keydown",function(e){if(e.key==="Enter")unlock()});' +
'async function load(){$("#topMeta").innerHTML="Loading\\u2026";try{DATA=await api({action:"overview"});render()}catch(e){$("#topMeta").innerHTML="<span class=dn>"+esc(e.message)+"</span>";if(!DATA)$("#kpis").innerHTML="<div class=empty>"+esc(e.message)+"</div>"}}' +
'$("#refresh").addEventListener("click",load);' +
'function render(){var D=DATA,P=D.platform,A=D.activity,S=D.stats||{};' +
'$("#topMeta").innerHTML="Generated "+when(D.generated_at)+" \\u00b7 Supabase <b>"+D.latency_ms+" ms</b>"+(D.deployment.commit?" \\u00b7 build <b class=tick>"+esc(D.deployment.commit)+"</b>":"");' +
'var live=D.members.filter(function(m){return m.summary&&!m.summary.demo}).length;' +
'$("#kpis").innerHTML=[["Members",D.members.length,A.active7+" active this week, "+A.active30+" this month"],["Live books",live,(P.books-live)+" still on demo data, "+A.never+" never saved"],["Capital on the platform",gbp(P.costOpen),P.positionsOpen+" open positions, "+P.units+" units"],["Revenue realised",gbp(P.revenue),P.sold+" sales across every book"],["Clients on the platform",P.clients,P.requestsOpen+" open sourcing requests"],["Owed to members",gbp(P.owed),P.invoicesOpen+" open invoices",P.owed>0?"dn":""],["Snapshots",S.history||0,kb(S.history_bytes)+" held, last 120 per book"],["Database",(S.db_bytes/1e6).toFixed(0)+" MB","of 500 MB on the free tier"]].map(function(k){return "<div class=kpi><div class=l>"+k[0]+"</div><div class=\\"v "+(k[3]||"")+"\\">"+k[1]+"</div><div class=s>"+k[2]+"</div></div>"}).join("");' +
'$("#insSub").textContent=D.insights.length+" item"+(D.insights.length===1?"":"s");$("#insights").innerHTML=D.insights.map(function(i){return "<div class=al><span class=\\"sig "+i.lvl+"\\"></span><div><div class=t>"+esc(i.t)+"</div><div class=d>"+esc(i.d)+"</div></div></div>"}).join("");' +
'var dp=D.deployment;$("#deploy").innerHTML="<div class=stat-row><div class=stat><div class=l>Environment</div><div class=v>"+esc(dp.env)+"</div></div><div class=stat><div class=l>Region</div><div class=v>"+esc(dp.region||"\\u2014")+"</div></div><div class=stat><div class=l>Node</div><div class=v>"+esc(dp.node)+"</div></div></div><div class=small style=\\"margin-top:10px\\">"+(dp.commit?"Commit <span class=code>"+esc(dp.commit)+"</span> on "+esc(dp.branch||"?")+(dp.message?": "+esc(dp.message):""):"Not a Vercel build")+"</div>"+(dp.project?"<div class=small style=\\"margin-top:6px\\">Production: <a href=\\"https://"+esc(dp.project)+"\\" target=_blank rel=noopener>"+esc(dp.project)+"</a></div>":"");' +
'renderMembers();' +
'$("#platform").innerHTML=[["Books",P.books],["Live",P.live],["Open positions",P.positionsOpen],["Units",P.units],["Capital deployed",gbp(P.costOpen)],["Sales",P.sold],["Revenue",gbp(P.revenue)],["Clients",P.clients],["Open requests",P.requestsOpen],["Open invoices",P.invoicesOpen],["Owed",gbp(P.owed)],["Cash on ledgers",gbp(P.cash)]].map(function(s){return "<div class=stat><div class=l>"+s[0]+"</div><div class=v>"+s[1]+"</div></div>"}).join("");' +
'bars("#savesBars",D.saves);$("#savesSub").textContent=D.saves.reduce(function(a,b){return a+b.n},0)+" snapshots in 30 days; "+A.saved7+" member"+(A.saved7===1?"":"s")+" saved this week.";' +
'bars("#signupBars",D.signups);$("#signupSub").textContent=D.signups.reduce(function(a,b){return a+b.n},0)+" new";$("#actSub").textContent=A.active7+" signed in this week, "+A.active30+" this month.";' +
'$("#htable").innerHTML="<thead><tr><th>Taken</th><th>Member</th><th>Why</th><th class=r>Size</th></tr></thead><tbody>"+(D.history.map(function(h){return "<tr><td>"+when(h.taken_at)+"</td><td>"+esc(h.email)+"</td><td class=small>"+esc(h.reason)+"</td><td class=\\"r small\\">"+kb(h.bytes)+"</td></tr>"}).join("")||"<tr><td colspan=4 class=empty>No snapshots yet.</td></tr>")+"</tbody>";' +
'$("#sbBox").innerHTML="<div class=stat-row><div class=stat><div class=l>Latency</div><div class=v>"+D.latency_ms+"<small>ms, six calls</small></div></div><div class=stat><div class=l>Database</div><div class=v>"+(S.db_bytes/1e6).toFixed(1)+"<small>MB</small></div></div><div class=stat><div class=l>Books</div><div class=v>"+kb(S.book_bytes)+"</div></div><div class=stat><div class=l>Users</div><div class=v>"+(S.users||0)+"</div></div></div><div class=small style=\\"margin-top:10px\\">Project <span class=code>"+esc((D.supabase.url||"").replace(/^https?:\\/\\//,""))+"</span>. Row-level security on every table; this page reads with the service role from the server only.</div>";' +
'$("#ttable").innerHTML="<thead><tr><th>Table</th><th class=r>Rows</th><th class=r>Size</th></tr></thead><tbody>"+((S.tables||[]).map(function(t){return "<tr><td class=tick>"+esc(t.name)+"</td><td class=r>"+Number(t.rows).toLocaleString()+"</td><td class=\\"r small\\">"+kb(t.bytes)+"</td></tr>"}).join(""))+"</tbody>";' +
'$("#fnBox").innerHTML=D.functions.map(function(f){var c=f.state==="live"?"green":f.state==="not deployed"?"grey":"red";return "<div style=\\"display:flex;align-items:center;gap:8px;padding:7px 0;border-bottom:1px solid var(--line)\\"><span class=\\"dot "+c+"\\"></span><span class=tick>"+esc(f.fn)+"</span><span class=sp style=flex:1></span><span class=small>"+esc(f.state)+(f.code?" \\u00b7 "+f.code:"")+" \\u00b7 "+f.ms+" ms</span></div>"}).join("")+"<div class=small style=\\"margin-top:10px\\">Not deployed is the honest state until each function exists with its own secret. The app shows the same thing on its Connections tab.</div>";' +
'$("#atable").innerHTML="<thead><tr><th>When</th><th>Action</th><th>Target</th><th>IP</th></tr></thead><tbody>"+(D.audit.map(function(a){return "<tr><td>"+when(a.at)+"</td><td>"+esc(a.action)+"</td><td class=small>"+esc(a.target||"")+"</td><td class=\\"small tick\\">"+esc(a.ip||"")+"</td></tr>"}).join("")||"<tr><td colspan=4 class=empty>Nothing done from this page yet.</td></tr>")+"</tbody>";}' +
'function bars(sel,arr){var max=Math.max(1,Math.max.apply(null,arr.map(function(b){return b.n})));$(sel).innerHTML=arr.map(function(b){return "<i title=\\""+b.day+": "+b.n+"\\" class=\\""+(b.n?"":"zero")+"\\" style=\\"height:"+(b.n?Math.max(6,Math.round(b.n/max*100)):2)+"%\\"></i>"}).join("")}' +
'function renderMembers(){var D=DATA;var q=Q.toLowerCase();var list=D.members.filter(function(m){if(q&&!((m.email||"")+" "+((m.book&&m.book.name)||"")).toLowerCase().includes(q))return false;if(CHIP==="live")return m.summary&&!m.summary.demo;if(CHIP==="demo")return m.summary&&m.summary.demo;if(CHIP==="red")return m.health.score!=="green";if(CHIP==="nobook")return !m.book;return true});' +
'$$("#chips button").forEach(function(b){b.classList.toggle("on",b.dataset.c===CHIP)});$("#mcount").textContent=list.length+" of "+D.members.length;' +
'$("#mtable").innerHTML="<thead><tr><th>Member</th><th>Workspace</th><th>Joined</th><th>Last sign-in</th><th class=r>Open</th><th class=r>Sold</th><th class=r>Revenue</th><th class=r>Clients</th><th class=r>Owed</th><th class=r>Cash</th><th class=r>Book</th><th>Last save</th><th class=r>Snapshots</th></tr></thead><tbody>"+(list.map(function(m){var s=m.summary||{};return "<tr class=row data-id=\\""+esc(m.id)+"\\"><td><span class=\\"dot "+m.health.score+"\\"></span>"+esc(m.email)+(m.confirmed?"":" <span class=\\"pill amber\\">unconfirmed</span>")+"<div class=small style=\\"padding-left:16px\\">"+esc(m.health.why)+"</div></td><td>"+(m.book?esc(m.book.name||s.workspace)+(s.demo?" <span class=pill>demo</span>":" <span class=\\"pill green\\">live</span>"):"<span class=mute>\\u2014</span>")+"</td><td class=small>"+when(m.created_at)+"</td><td class=small>"+ago(m.last_sign_in_at)+"</td><td class=r>"+(m.book?s.open:"")+"</td><td class=r>"+(m.book?s.sold:"")+"</td><td class=r>"+(m.book?gbp(s.revenue):"")+"</td><td class=r>"+(m.book?s.clients:"")+"</td><td class=\\"r "+(s.owed>0?"dn":"")+"\\">"+(m.book&&s.owed?gbp(s.owed):"")+"</td><td class=r>"+(m.book?gbp(s.cash):"")+"</td><td class=\\"r small\\">"+(m.book?kb(m.book.bytes):"")+"</td><td class=small>"+(m.book?ago(m.book.saved_at):"never")+"</td><td class=r>"+m.snapshots+"</td></tr>"}).join("")||"<tr><td colspan=13 class=empty>Nobody matches.</td></tr>")+"</tbody>";' +
'$$("#mtable tr.row").forEach(function(r){r.addEventListener("click",function(){openMember(r.dataset.id)})})}' +
'$("#q").addEventListener("input",function(e){Q=e.target.value;renderMembers()});$$("#chips button").forEach(function(b){b.addEventListener("click",function(){CHIP=b.dataset.c;renderMembers()})});' +
'function openMember(id){var m=DATA.members.find(function(x){return x.id===id});if(!m)return;var s=m.summary||{};var h="";' +
'h+="<div class=dsec><div style=\\"display:flex;gap:6px;flex-wrap:wrap;align-items:center\\"><span class=\\"pill "+m.health.score+"\\">"+esc(m.health.why)+"</span>"+(m.book?(s.demo?"":"<span class=\\"pill green\\">live</span>"):"")+(s.entity?"<span class=pill>"+esc(s.entity==="ltd"?"limited company":"sole trader")+"</span>":"")+(s.whatsapp?"<span class=\\"pill blue\\">WhatsApp set</span>":"")+"</div></div>";' +
'h+="<div class=dsec><h4>Account</h4><div class=metrics><div class=metric><div class=l>Joined</div><div class=v>"+when(m.created_at)+"</div></div><div class=metric><div class=l>Last sign-in</div><div class=v>"+ago(m.last_sign_in_at)+"</div></div><div class=metric><div class=l>Provider</div><div class=v>"+esc(m.provider)+"</div></div></div><div class=small style=\\"margin-top:8px\\">User id <span class=code>"+esc(m.id)+"</span></div></div>";' +
'if(m.book){h+="<div class=dsec><h4>Book</h4><div class=metrics><div class=metric><div class=l>Workspace</div><div class=v>"+esc(m.book.name||s.workspace)+"</div></div><div class=metric><div class=l>Last save</div><div class=v>"+when(m.book.saved_at)+"</div></div><div class=metric><div class=l>Size</div><div class=v>"+kb(m.book.bytes)+"</div></div><div class=metric><div class=l>Open positions</div><div class=v>"+s.open+"<small style=\\"font-size:11px;color:var(--ink-3);margin-left:4px\\">"+s.units+" units</small></div></div><div class=metric><div class=l>Capital deployed</div><div class=v>"+gbp(s.costOpen)+"</div></div><div class=metric><div class=l>Sales</div><div class=v>"+s.sold+"</div></div><div class=metric><div class=l>Revenue</div><div class=v>"+gbp(s.revenue)+"</div></div><div class=metric><div class=l>Cost of sold</div><div class=v>"+gbp(s.costSold)+"</div></div><div class=metric><div class=l>Last sale</div><div class=v>"+(s.lastSale?when(s.lastSale+"T12:00:00").split(" ")[0]+" "+when(s.lastSale+"T12:00:00").split(" ")[1]:"\\u2014")+"</div></div><div class=metric><div class=l>Clients</div><div class=v>"+s.clients+"<small style=\\"font-size:11px;color:var(--ink-3);margin-left:4px\\">"+s.clientsWithContact+" with contact</small></div></div><div class=metric><div class=l>Open requests</div><div class=v>"+s.requestsOpen+"</div></div><div class=metric><div class=l>Open invoices</div><div class=v>"+s.invoicesOpen+"<small style=\\"font-size:11px;color:var(--ink-3);margin-left:4px\\">"+gbp(s.owed)+"</small></div></div><div class=metric><div class=l>Cash on ledger</div><div class=v>"+gbp(s.cash)+"</div></div><div class=metric><div class=l>Tax reserve</div><div class=v>"+gbp(s.taxReserve)+"</div></div><div class=metric><div class=l>Ledger entries</div><div class=v>"+s.ledgerEntries+"</div></div></div><div class=small style=\\"margin-top:8px\\">"+m.snapshots+" snapshot"+(m.snapshots===1?"":"s")+(m.last_snapshot?", latest "+ago(m.last_snapshot):"")+". Connected: "+(s.integrations&&s.integrations.length?esc(s.integrations.join(", ")):"nothing yet")+".</div></div>"}' +
'h+="<div class=dsec><h4>Actions</h4><div class=btnrow><button class=\\"btn sm secondary\\" data-act=magiclink>Sign-in link</button>"+(m.book?"<button class=\\"btn sm secondary\\" data-act=snapshot>Snapshot now</button><button class=\\"btn sm secondary\\" data-act=export>Download book</button>":"")+"<button class=\\"btn sm danger\\" data-act=delete>Delete member</button></div><div class=note style=\\"margin-top:10px\\">Sign-in link creates a one-time magic link you can paste to them. Snapshot writes today\\u2019s book to history as an admin snapshot. Download gives you their raw book as JSON. Delete removes the account, the book and every snapshot; it cannot be undone.</div></div>";' +
'openDrawer(m.email,h);' +
'$$("#dBody [data-act]").forEach(function(b){b.addEventListener("click",function(){memberAction(m,b.dataset.act,b)})})}' +
'async function memberAction(m,act,btn){try{if(act==="magiclink"){btn.disabled=true;var r=await api({action:"magiclink",email:m.email,redirect:location.origin});btn.disabled=false;modal("<h3>Sign-in link for "+esc(m.email)+"</h3><p>One use, expires in an hour. Send it to them however you talk.</p><div class=code style=\\"padding:8px 10px\\">"+esc(r.link||"The auth server returned no link; check Site URL in Supabase.")+"</div><div class=acts><button class=\\"btn secondary\\" data-close>Close</button>"+(r.link?"<button class=btn id=cp>Copy</button>":"")+"</div>");var cp=$("#cp");if(cp)cp.addEventListener("click",function(){try{navigator.clipboard.writeText(r.link)}catch(e){}toast("Copied");closeModal()});}' +
'else if(act==="snapshot"){btn.disabled=true;await api({action:"snapshot",owner:m.id});toast("Snapshot taken");await load();openMember(m.id)}' +
'else if(act==="export"){btn.disabled=true;var e=await api({action:"export",owner:m.id});btn.disabled=false;var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(e.state)],{type:"application/json"}));a.download="sizemill-"+(m.email||"member").replace(/[^a-z0-9]+/gi,"-")+"-"+new Date().toISOString().slice(0,10)+".json";a.click();toast("Book downloaded")}' +
'else if(act==="delete"){modal("<h3>Delete "+esc(m.email)+"?</h3><p>Their account, book and every snapshot go. Type DELETE to confirm.</p><input id=del_c class=search style=\\"width:100%\\" placeholder=DELETE><div class=acts><button class=\\"btn secondary\\" data-close>Keep</button><button class=\\"btn danger\\" id=del_ok>Delete</button></div>");$("#del_ok").addEventListener("click",async function(){try{$("#del_ok").disabled=true;await api({action:"deleteUser",id:m.id,email:m.email,confirm:$("#del_c").value.trim()});closeModal();closeDrawer();toast("Deleted");load()}catch(e){toast(e.message);$("#del_ok").disabled=false}})}' +
'}catch(e){btn.disabled=false;toast(e.message)}}' +
'$("#inv_go").addEventListener("click",async function(){var em=$("#inv_email").value.trim();if(!em){toast("Email, please");return}$("#inv_go").disabled=true;try{await api({action:"invite",email:em});toast("Invite sent to "+em);$("#inv_email").value="";load()}catch(e){toast(e.message)}finally{$("#inv_go").disabled=false}});' +
'$("#csv").addEventListener("click",function(){if(!DATA)return;var rows=[["email","joined","last_sign_in","health","workspace","live","open","units","capital","sold","revenue","clients","open_requests","open_invoices","owed","cash","book_kb","last_save","snapshots"]];DATA.members.forEach(function(m){var s=m.summary||{};rows.push([m.email,m.created_at,m.last_sign_in_at||"",m.health.score,(m.book&&m.book.name)||"",m.book?(s.demo?"demo":"live"):"none",s.open||0,s.units||0,Math.round(s.costOpen||0),s.sold||0,Math.round(s.revenue||0),s.clients||0,s.requestsOpen||0,s.invoicesOpen||0,Math.round(s.owed||0),Math.round(s.cash||0),m.book?Math.round(m.book.bytes/1024):0,(m.book&&m.book.saved_at)||"",m.snapshots])});var csv=rows.map(function(r){return r.map(function(v){return "\\""+String(v).replace(/"/g,"\\"\\"")+"\\""}).join(",")}).join("\\n");var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="sizemill-members-"+new Date().toISOString().slice(0,10)+".csv";a.click()});' +
'if(SECRET){$("#gate").classList.add("hidden");load()}else{setTimeout(function(){$("#g_secret").focus()},50)}' +
'</script></body></html>';
